### ISSUE TITLE
[Audit/7.11] APM audit

### ISSUE THREAD

**Issue by katrin-freihofner** [elastic/observability-design#11]
Related master audit issue https://github.com/elastic/observability-design/issues/7

### Charts

- [x] Sometimes the tooltip is missing https://github.com/elastic/kibana/issues/85793
<details>
<summary>View screens</summary>
It seems to me that there is no data at the time I was hovering over in the chart at the bottom. I think in that case we should anyhow show a tooltip with an empty state.
<img width="1581" alt="Screenshot 2020-12-10 at 15 58 09" src="https://user-images.githubusercontent.com/20965076/101798637-99720e80-3b0b-11eb-92c9-e601f837143f.png">
</details>

- [x] Sometimes the tooltips are misplaced (charts enhancement issue https://github.com/elastic/elastic-charts/issues/922)
<details>
<summary>View screens</summary>

<img width="1343" alt="Screenshot 2020-12-10 at 15 56 12" src="https://user-images.githubusercontent.com/20965076/101799963-02a65180-3b0d-11eb-916b-2a9454e40033.png">

</details>

### Settings
- [x] The settings menu is not clickable on small screens https://github.com/elastic/kibana/issues/85744
<details>
<summary>View screens</summary>
I was not able to open this menu.
<img width="694" alt="Screenshot 2020-12-10 at 15 54 43" src="https://user-images.githubusercontent.com/20965076/101799842-e4d8ec80-3b0c-11eb-8646-23afb9f426dc.png">
</details>

### Small screens

- [x] Responsive views (https://github.com/elastic/kibana/issues/85747 + https://github.com/elastic/kibana/issues/85752)
<details>
<summary>View screens</summary>
I think we have a couple of views that we could improve when it comes to small screens. https://github.com/elastic/kibana/issues/85747
<img width="785" alt="Screenshot 2020-12-10 at 15 45 16" src="https://user-images.githubusercontent.com/20965076/101799619-a93e2280-3b0c-11eb-92ff-7972d37c4c48.png">

Here is another example (https://github.com/elastic/kibana/issues/85752)
<img width="617" alt="Screenshot 2020-12-10 at 15 45 24" src="https://user-images.githubusercontent.com/20965076/101799637-b0653080-3b0c-11eb-9da8-2be32fb2e0cd.png">
</details>

### Charts

- [x] I found a couple of issues with the new charts. The legend and (time) legend is hard to read. The legend becomes scrollable very quickly.
<details>
<summary>View screens</summary>
This is an example where there is a lot of space but the legend is not fully shown anyhow.
<img width="1125" alt="Screenshot 2020-12-10 at 17 10 11" src="https://user-images.githubusercontent.com/20965076/101798428-5ca61780-3b0b-11eb-8401-f0118757389e.png">

This is an example where I think the values are very hard to read
<img width="567" alt="Screenshot 2020-12-10 at 17 09 46" src="https://user-images.githubusercontent.com/20965076/101798526-721b4180-3b0b-11eb-97e8-4df0aba27b33.png">

We have the same challenge with the legend
<img width="747" alt="Screenshot 2020-12-10 at 15 46 32" src="https://user-images.githubusercontent.com/20965076/101798762-c1fa0880-3b0b-11eb-814c-69bf934fe78b.png">

This example shows that the timestamps are hard to read (enhancement issue https://github.com/elastic/kibana/issues/84481)
<img width="745" alt="Screenshot 2020-12-10 at 17 06 07" src="https://user-images.githubusercontent.com/20965076/101798565-7cd5d680-3b0b-11eb-89fe-226b0ab62ecd.png">
</details>

### Filters

- [x] Empty filter options https://github.com/elastic/observability-design/issues/11#issuecomment-744294316
<details>
<summary>View screens</summary>
I'm wondering why we show empty options.

<img width="291" alt="Screenshot 2020-12-10 at 14 23 49" src="https://user-images.githubusercontent.com/20965076/101799304-4ba9d600-3b0c-11eb-9f2c-cf6a4c6533c8.png">
</details>

### Alerts

- [x] Inconsistent wording https://github.com/elastic/kibana/issues/85753
<details>
<summary>View screens</summary>
In APM we say "View active alerts" in the other apps this button label says "Mangage alerts".
<img width="279" alt="Screenshot 2020-12-10 at 15 44 23" src="https://user-images.githubusercontent.com/20965076/101799377-61b79680-3b0c-11eb-9202-141f06a1cda9.png">
</details>

### Others issues
- [x] Text is not centered vertically https://github.com/elastic/kibana/issues/85755
<details>
<summary>View screens</summary>
It's a small detail but in some tables (I think the ones using spark lines) the text is not perfectly aligned.
<img width="1231" alt="Screenshot 2020-12-10 at 15 44 31" src="https://user-images.githubusercontent.com/20965076/101799605-a2afab00-3b0c-11eb-9e34-5189ff63998b.png">
</details>

- [x] There are no emply states for some panels https://github.com/elastic/observability-design/issues/11#issuecomment-742848146
<details>
<summary>View screens</summary>
I'm not sure if maybe there is a PR still open to fill those panels?
<img width="1140" alt="Screenshot 2020-12-10 at 17 09 39" src="https://user-images.githubusercontent.com/20965076/101800063-1f428980-3b0d-11eb-8be2-9a1b9401fc32.png">
<img width="1067" alt="Screenshot 2020-12-10 at 17 06 37" src="https://user-images.githubusercontent.com/20965076/101800069-223d7a00-3b0d-11eb-8a4a-3742f52ba57c.png">
</details>

- [x] Adding new environments? https://github.com/elastic/observability-design/issues/11#issuecomment-744291850
<details>
<summary>View screens</summary>
I'm not sure I understand why we give users the option to create a new value here.
<img width="562" alt="Screenshot 2020-12-10 at 15 49 12" src="https://user-images.githubusercontent.com/20965076/101800752-e7881180-3b0d-11eb-907a-f32622ac3ef3.png">
</details>

**Comment by smith** [comment]
@katrin-freihofner 

> I'm not sure if maybe there is a PR still open to fill those panels?

Yes:

* elastic/kibana#84634
* elastic/kibana#81721
* elastic/kibana#81720

Any of these that don't make the 7.11 freeze will have their empty boxes removed.

**Comment by formgeist** [comment]
> Adding new environments? I'm not sure I understand why we give users the option to create a new value here.

The user has the ability to define environments that are not yet discoverable because the data is yet to be ingested. Could be a new environment they're planning on setting in their agents to filter out their data, they can immediately define configs for those services as they reach the server and get their configs. Not exactly a standard flow, but it's possible.

**Comment by formgeist** [comment]
> Empty filter options. I'm wondering why we show empty options.

Good point. The filter option should not be clickable but instead show a disabled state and tooltip that no options are available. Seeing as we're planning to [remove the UI filters](https://github.com/elastic/kibana/issues/84526) in the coming release, I'm not sure it's worth improving it as this time.

**Comment by formgeist** [comment]
> I found a couple of issues with the new charts. The legend and (time) legend is hard to read. The legend becomes scrollable very quickly.

I believe we have raised the issue with the chart teams around making the listing of legends more dynamic rather than ending up hiding x number outside the legend container. I just can't find the issue at this time. The units in the "time spent" chart should be fixed in the latest `master`, I'll double-check. You mention a problem with the number of buckets in the x-axis, which already has an [enhancement issue](https://github.com/elastic/kibana/issues/84481) open.

**Comment by formgeist** [comment]
> Responsive views. I think we have a couple of views that we could improve when it comes to small screens.

Great point - and especially with the Service inventory, which is the landing page for APM. I'd consider both bugs, and raise this in a new issue. We need to consider removing e.g. the sparklines on smaller viewports (right now we're not even showing the service name link). Secondly, the smallest breakpoint where we display cards instead of table rows, definitely need some ❤️

**Comment by formgeist** [comment]
Closing - all the points in the audit have been addressed by new issues - those they have reasons like known issues or features to be replaced have been commented on as well.
