### ISSUE TITLE
Design audit APM UI 7.12

### ISSUE THREAD

**Issue by hbharding** [elastic/observability-design#28]
Overall great stuff @formgeist. I didn't find any unknown bugs, but I left some comments/ideas for improvements for the correlations flyout.

# APM UI audit

Tested on: Release obs cluster (7.12)

### Correlations
- [x] Errors tab throws an error (fun one to say) but this is already a known problem we have an issue for:  https://github.com/elastic/kibana/issues/93443

### Removal of UI filters sidebar

No bugs / layout issues found. I noticed I can't see the UI Filters sidebar anymore 😄 

### Correlations

- [x] Add spacing between tabs and "View correlations" button for small screens. https://github.com/elastic/kibana/issues/93901
- [x] "Learn more about default fields" should probably open docs in a new tab like we do for our docs links in the global "help" dropdown. Use "external" prop for EuiLink to indicate behavior. https://github.com/elastic/kibana/issues/93902
- [x] Add a tooltip description to the "Impact" column header described what this is, like we do for transactions. It's unclear what this is showing - I initially assumed it was related to the number in the next column "% of slow transactions" https://github.com/elastic/kibana/issues/93903
- [x] Consider renaming the "Actions" column header to "Filter" since the only related actions are for filtering. I was confused by the "zoom in" / "zoom out" icons and assumed it might zoom the chart above. https://github.com/elastic/kibana/issues/93904
- [x] It would be helpful if users could select/focus a table rows so that the bars that appear in the chart above stay persistent. The chart updates when hovering on table rows, which makes it impossible to hover on the chart and see the value for a particular field name. https://github.com/elastic/kibana/issues/93907
- [x] Clicking on a legend item in the latency distribution chart hides the bar chart. Since we're only showing 1 piece of data (or 2 when user hovers on the table), I don't think this provides any value. I know this toggle visibility feature is built into EuiCharts.... and I just asked the charts team if there's an option to disable this feature and learned that there is not... so I created an issue for them to see if we can make the toggle visibility feature optional https://github.com/elastic/elastic-charts/issues/1055 https://github.com/elastic/kibana/issues/93908

<details>
<summary>View screens</summary>

![image](https://user-images.githubusercontent.com/847805/110005521-93449600-7ce6-11eb-8de9-53134842c3f8.png)
---
![image](https://user-images.githubusercontent.com/847805/110013894-29c98500-7cf0-11eb-89fc-0ad312c0305b.png)
</details>

**Comment by formgeist** [comment]
@hbharding Thanks for your audit - you found some really good issues, so I've gone ahead and created Kibana issues for them all 👍
