### ISSUE TITLE
[Audit] APM 7.13

### ISSUE THREAD

**Issue by katrin-freihofner** [elastic/observability-design#39]
Please make sure you add this to the GitHub board for the next release.

# APM 7.13 audit
[Audit meta issue](https://github.com/elastic/observability-design/issues/35)

Tested on: master built locally

## 🐛 Bugs

- [x] Service list is not responsive, service names not visible -> https://github.com/elastic/kibana/issues/97674

**Duplicate of https://github.com/elastic/kibana/issues/94828**

<img width="842" alt="Screenshot 2021-04-20 at 16 38 41" src="https://user-images.githubusercontent.com/20965076/115431886-16be3600-a206-11eb-90bd-a7e9d856390f.png">

### Remove the filter when navigating with the breadcrumbs?

- [ ] I'm not sure if this behavior is intended: I filtered for one instance using the chart. I clicked on the "Services" breadcrumb. The list I got was filtered, I was surprised by that.
<details>
<summary>View screens</summary>
<img width="1680" alt="Screenshot 2021-04-20 at 16 36 14" src="https://user-images.githubusercontent.com/20965076/115431310-736d2100-a205-11eb-98bd-ac8bf2efa22e.png">
</details>

### It's hard to grasp that the view has been filtered https://github.com/elastic/kibana/issues/97860

- [ ] I clicked one of the instances in the chart and did not realize immediately that the view has been filtered. Additionally, on smaller screens, it's hard to see the input in the search bar.
<details>
<summary>View screens</summary>
![instances](https://user-images.githubusercontent.com/20965076/115431603-c8109c00-a205-11eb-90d0-48c5224c8810.gif)

<img width="708" alt="Screenshot 2021-04-20 at 16 34 52" src="https://user-images.githubusercontent.com/20965076/115431558-bc24da00-a205-11eb-9251-1af91a67e390.png">

</details>

### Some breadcrumbs are linking to the same view 
- [ ] "APM" and "Services" breadcrumb link to the same view. Also, in this example, "opbeans-java" does not navigate anywhere. I think it would make sense to drop the "APM" breadcrumb or include it to have "APM: Services" and "opbeans-java: overview"
<details>
<summary>View screens</summary>
<img width="344" alt="Screenshot 2021-04-20 at 16 33 09" src="https://user-images.githubusercontent.com/20965076/115431993-36edf500-a206-11eb-9485-23105063fac5.png">
</details>

### Previous period comparison
- [ ] Dark mode: the color used for showing the previous period is hard to see https://github.com/elastic/kibana/issues/97862
<details>
<summary>View screens</summary>
<img width="543" alt="Screenshot 2021-04-20 at 16 23 41" src="https://user-images.githubusercontent.com/20965076/115432459-abc12f00-a206-11eb-9866-edc0b3f82906.png">

</details>

- [ ] Legend/tooltip inconsistent https://github.com/elastic/kibana/issues/97863
I guess sometimes there is no data in the previous period and that is why the tooltip/legend is empty. I wonder if that is ok or we should add something like "n/a" in this case? 
<details>
<summary>View screens</summary>
<img width="817" alt="Screenshot 2021-04-20 at 16 20 37" src="https://user-images.githubusercontent.com/20965076/115432703-f642ab80-a206-11eb-9baa-39f46aeb97b4.png">
</details>

- [ ] Tooltip is hard to read https://github.com/elastic/observability-design/issues/30
I think this tooltip is a bit hard to read, maybe a bit more whitespace between the instances could help?
Also, I'm wondering if it makes sense to add a zoom functionality here?
<details>
<summary>View screens</summary>
<img width="912" alt="Screenshot 2021-04-20 at 16 18 59" src="https://user-images.githubusercontent.com/20965076/115433109-749f4d80-a207-11eb-97e9-c3e1c8f8d8ac.png">

</details>

**Comment by formgeist** [comment]
@katrin-freihofner Thanks for the audit! As always, some great feedback and potential enhancements we can address. I have a few responses to some of the discoveries you made.

> **Remove the filter when navigating with the breadcrumbs?**
> I'm not sure if this behavior is intended: I filtered for one instance using the chart. I clicked on the "Services" breadcrumb. The list I got was filtered, I was surprised by that.

We do intend the filters to persist through the view. If you're filtering a single service instance that same singled-out data should be shown in the subsequence views like the Transactions list or detail pages. The question is if we want to treat going back "up" to the inventory with the same persistence. IMO we might actually want to determine this as another flow, but I'm not sure this is easily feasible in the current form where the KQL bar is always going to persist when it's available. cc @alex-fedotyev 

> **It's hard to grasp that the view has been filtered**
> I clicked one of the instances in the chart and did not realize immediately that the view has been filtered. Additionally, on smaller screens, it's hard to see the input in the search bar.

I agree that the search input is not responding well to smaller viewport sizes. We should fix this in the release, and consider it a bug. I've opened https://github.com/elastic/kibana/issues/97860 to track this.

The visibility into what's currently my applied filters is difficult, but perhaps it'll be fixed by the new page header or even the filters project. I don't see a good temporary or quick solution to fixing this right now as the row doesn't currently lend itself to be "sticky" at the top.

> **Some breadcrumbs are linking to the same view**
> "APM" and "Services" breadcrumb link to the same view. Also, in this example, "opbeans-java" does not navigate anywhere. I think it would make sense to drop the "APM" breadcrumb or include it to have "APM: Services" and "opbeans-java: overview"

I imagine the breadcrumb will always indicate what app you're currently in within the solution. This is also the case for our upcoming solution nav implementation. I understand that the APM item is clickable and just takes you to the Services inventory because that's the first page in the list of global APM views. I wonder what we'll do in any of the other apps where we'll want to visibly indicate the selected app, but some apps don't have a landing page per se.

> ### Previous period comparison
> **Tooltip is hard to read**
> I think this tooltip is a bit hard to read, maybe a bit more whitespace between the instances could help?
> Also, I'm wondering if it makes sense to add a zoom functionality here?

We are planning on more [enhancements](https://github.com/elastic/observability-design/issues/30) to the interactions within the scatterplot for the instances. The tooltip can also be enhanced slightly in this iteration.

**Comment by katrin-freihofner** [comment]
@formgeist thank you! If we have time in today's (or next weeks) design sync we could discuss the breadcrumb issue with the other team members.

**Comment by formgeist** [comment]
Opened https://github.com/elastic/observability-design/issues/53 for general alignment on the breadcrumbs. Closing out this audit issue as most of the issues have been addressed.
