### ISSUE TITLE
[APM] (Meta) Correlations UX (GA)

### ISSUE THREAD

**Issue by formgeist** [elastic/observability-design#68]
# Summary

In anticipation of making the Correlations feature GA, we're looking to improve the UX and generally polish the feature in the coming release.

# Issues

- [x] https://github.com/elastic/observability-design/issues/75
- [ ] ~https://github.com/elastic/kibana/issues/95272~ Will not be included in 7.15
- [x] https://github.com/elastic/observability-design/issues/69
