### ISSUE TITLE
[Observability] 7.14: Responsive layout fixes

### ISSUE THREAD

**Issue by formgeist** [elastic/observability-design#71]
# Summary
The new EUI page layout including the collapsible side nav is causing the main container to break. We should be changing that layouts to mostly 1 column-based and changing the table to mobile layout at breakpoint `l`.

# Issues

### Observability Overview
- [x] Metrics panel: Change the table to mobile layout at breakpoint `l` : https://github.com/elastic/kibana/issues/104119
<details>
<summary>View screens</summary>
<img width="1312" alt="Screenshot 2021-07-01 at 15 55 31" src="https://user-images.githubusercontent.com/4104278/124136185-d3453b00-da84-11eb-95d1-3d39345a33c9.png">
</details>

- [x] Observability overview: Move to single column layout: https://github.com/elastic/kibana/issues/104121
<details>
<summary>View screens</summary>
<img width="1104" alt="Screenshot 2021-07-01 at 15 55 40" src="https://user-images.githubusercontent.com/4104278/124136198-d5a79500-da84-11eb-941b-c52945656639.png">
</details>

### Observability wide
- [x] Metrics: https://github.com/elastic/kibana/issues/104117
<details>
<summary>View screens</summary>
<img width="1104" alt="Screen Shot 2021-07-01 at 8 22 47 AM" src="https://user-images.githubusercontent.com/455281/124141013-3fed1500-da46-11eb-9d88-c3f437bc19e5.png">
</details>

- [x] Logs: https://github.com/elastic/kibana/issues/104118
<details>
<summary>View screens</summary>
<img width="1104" alt="Screen Shot 2021-07-01 at 8 28 12 AM" src="https://user-images.githubusercontent.com/455281/124141167-69a63c00-da46-11eb-9a20-931efe518b10.png">
</details>

- [x] Uptime: https://github.com/elastic/kibana/issues/104130
<details>
<summary>View screens</summary>
<img width="1104" alt="Screen Shot 2021-07-01 at 8 30 40 AM" src="https://user-images.githubusercontent.com/455281/124141463-aeca6e00-da46-11eb-9084-43ddfaa0f01f.png">
</details>

- [x] APM: https://github.com/elastic/kibana/issues/103881
<details>
<summary>View screens</summary>
<img width="1104" alt="Screen Shot 2021-07-01 at 8 30 46 AM" src="https://user-images.githubusercontent.com/455281/124141429-a8d48d00-da46-11eb-8993-3c5305b19048.png">
</details>
