### ISSUE TITLE
[Audit/7.11] Uptime/Synthetics

### ISSUE THREAD

**Issue by formgeist** [elastic/observability-design#8]
# Uptime / Synthetics audit

Related master audit issue https://github.com/elastic/observability-design/issues/7

**Please note**
I wasn't able to test it fully because WIP PRs don't really lend themselves to the full experience.

### Monitor detail

- [x] When navigating to the monitor detail page, there's no indication of which page is active in the main navigation https://github.com/elastic/kibana/issues/85826
<details>
<summary>View screens</summary>
<img width="1665" alt="Screenshot 2020-12-10 at 09 25 26" src="https://user-images.githubusercontent.com/4104278/101741373-42981500-3aca-11eb-8326-0d0a094a20c0.png">
</details>

- [x] The monitor duration chart doesn't show the duration legend or unit formatted. The chart itself is also cut off because there's not enough room for the legend in the right side of the panel. https://github.com/elastic/kibana/issues/85827
<details>
<summary>View screens</summary>
<img width="823" alt="Screenshot 2020-12-10 at 10 22 33" src="https://user-images.githubusercontent.com/4104278/101752398-c1dd1700-3ad1-11eb-9427-2911d330f7e5.png">
</details>

- [x] Failed badge is using two separate red colors https://github.com/elastic/kibana/issues/85828
<details>
<summary>View screens</summary>
<img width="210" alt="Screenshot 2020-12-10 at 09 47 50" src="https://user-images.githubusercontent.com/4104278/101748419-d1a62c80-3acc-11eb-84d2-73cc01f2e86e.png">
</details>

- [x] Pings chart: The pings are stacked because there's one up and down, but the list shows that there's only one at the .45-minute https://github.com/elastic/kibana/issues/85829
<details>
<summary>View screens</summary>
<img width="1638" alt="Screenshot 2020-12-10 at 09 50 34" src="https://user-images.githubusercontent.com/4104278/101749043-91937980-3acd-11eb-975b-77baf591c366.png">
</details>

- [x] Both labels show location, but they handle the empty value differently.
<details>
<summary>View screens</summary>
<img width="731" alt="Screenshot 2020-12-10 at 09 57 00" src="https://user-images.githubusercontent.com/4104278/101749494-1bdbdd80-3ace-11eb-8733-6daf4aeda61b.png">
</details>

### Overview

- [x] Would it make sense to replace the "Investigate" option in the detail panel with the shared Observability actions menu?
<details>
<summary>View screens</summary>
<img width="411" alt="Screenshot 2020-12-10 at 09 55 28" src="https://user-images.githubusercontent.com/4104278/101749355-ee8f2f80-3acd-11eb-9841-a54997c46f88.png">
</details>

### Monitor detail

- [ ] Add additional descriptive copy to the experimental callout in the synthetics check detail. 
<details>
<summary>View screens</summary>
<img width="1637" alt="Screenshot 2020-12-10 at 09 31 10" src="https://user-images.githubusercontent.com/4104278/101741607-90148200-3aca-11eb-830d-9f7758a23f00.png">
</details>

- [x] The checks table jumps when a new check comes in, so the experience when inspecting a check is a little annoying. Wonder if this is something we want to do something about or are we moving to only display the proper detail page once it's ready? https://github.com/elastic/kibana/issues/90914
<details>
<summary>View screens</summary>

![Kapture 2020-12-10 at 09 35 42](https://user-images.githubusercontent.com/4104278/101744812-555f1980-3acb-11eb-9d80-fcb7c24fc144.gif)

</details>

- [x] Related to EUI: The image lightbox has some disadvantages and challenges with handling the overlay and Kibana elements beneath it. I would propose to enhance the close icon in the top right. Secondly, the navigation and timestamp should be in a panel or somewhere outside the image frame, as to not completely be hidden by the content of the website you're inspecting. https://github.com/elastic/kibana/issues/86877
<details>
<summary>View screens</summary>

![screencapture-localhost-5601-gqa-app-uptime-monitor-ZWxhc3RpYy1jbw-2020-12-10-10_04_39](https://user-images.githubusercontent.com/4104278/102076795-924b4900-3e08-11eb-989b-f2dd17d7daa8.png)

</details>

- [x] Show loading spinner on the images in the list of checks https://github.com/elastic/kibana/issues/86877
<details>
<summary>View screens</summary>

![Kapture 2020-12-10 at 10 39 38](https://user-images.githubusercontent.com/4104278/101754519-1da89f80-3ad4-11eb-997a-16616b718b70.gif)

</details>

### Step detail

- [x] Waterfall: Consider adding a min-height on the chart container.
<details>
<summary>View screens</summary>
<img width="1656" alt="Screenshot 2020-12-10 at 10 41 52" src="https://user-images.githubusercontent.com/4104278/101754768-63fdfe80-3ad4-11eb-9e54-4401e3a04d5f.png">
</details>

- [x] Header: Next check button should have the icon on the right https://github.com/elastic/kibana/pull/86878#issuecomment-750075382
<details>
<summary>View screens</summary>
<img width="564" alt="Screenshot 2020-12-10 at 10 51 20" src="https://user-images.githubusercontent.com/4104278/101755945-c3a8d980-3ad5-11eb-89a8-6d646ff1a89c.png">
</details>

**Comment by katrin-freihofner** [comment]
> * Both labels show location, but they handle the empty value differently

The location's name is "Unnamed-location". It is not empty, it should say something like "US-west".

**Comment by katrin-freihofner** [comment]
> * Would it make sense to replace the "Investigate" option in the detail panel with the shared Observability actions menu?

Yes, this is planned.

> Add additional descriptive copy to the experimental callout in the synthetics check detail.

Very good point!

> The checks table jumps when a new check comes in, so the experience when inspecting a check is a little annoying. Wonder if this is something we want to do something about or are we moving to only display the proper detail page once it's ready?

I agree, we should do something about it.

> Related to EUI: The image lightbox has some disadvantages and challenges with handling the overlay and Kibana elements beneath it. I would propose to enhance the close icon in the top right. Secondly, the navigation and timestamp should be in a panel or somewhere outside the image frame, as to not completely be hidden by the content of the website you're inspecting.

@formgeist could you upload that screenshot again - it does not display.

> Show loading spinner on the images in the list of checks

I'm not sure I understand this one. It is not a loading issue, there will never be an image for this step.

> Waterfall: Consider adding a min-height on the chart container.
Good point - I wonder if this is even a bug? I'm not sure if one would be able to click these rows.

> Next check button should have the icon on the right

Thanks for raising this.

**Comment by formgeist** [comment]
> @formgeist could you upload that screenshot again - it does not display.

Uploaded it again 👍 

> I'm not sure I understand this one. It is not a loading issue, there will never be an image for this step.

Sorry, I should have clarified. The "No image available" shows first before showing the step image, so you have this glitch effect on the table. I propose that it should show a loader before resulting in "No image available" empty state.

**Comment by katrin-freihofner** [comment]
> Sorry, I should have clarified. The "No image available" shows first before showing the step image, so you have this glitch effect on the table. I propose that it should show a loader before resulting in "No image available" empty state.

I see. Thank you!

**Comment by katrin-freihofner** [comment]
The only one left from this audit is "Add additional descriptive copy to the experimental callout in the synthetics check detail." - which will also be solved in the next release.
